---

resources:
- name: firehose-repo
  type: git
  source:
    branch: master
    uri: git@github.com:cf-platform-eng/splunk-firehose-nozzle
    private_key: {{github-deploy-key}}

jobs:
- name: unit-tests
  plan:
  - aggregate:
    - get: firehose-repo
      trigger: true
  - task: run-deployment-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: '1.6'
      inputs:
      - name: firehose-repo
      run:
        path: firehose-repo/ci/scripts/unit.sh
