---

resources:
- name: source-repo
  type: git
  source:
    branch: index-routing
    uri: https://github.com/cloudfoundry-community/splunk-firehose-nozzle.git
    ignore_paths:
      - ci/*

jobs:
- name: unit-tests
  plan:
  - aggregate:
    - get: source-repo
      trigger: true
  - task: run-deployment-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: '1.7'
      inputs:
      - name: source-repo
      run:
        path: source-repo/ci/unit.sh
