trafficcontroller:
  image: zlchen/trafficcontroller:1.1
  hostname: trafficcontroller
  ports:
    - "8081"
    - "9911"
  restart: always

nozzle:
  image: zlchen/nozzle:1.1
  hostname: nozzle
  ports:
    - "9912"
  environment:
    - API_ENDPOINT=http://trafficcontroller:9911
    - API_USER=admin
    - API_PASSWORD=admin
    - SPLUNK_TOKEN=1CB57F19-DC23-419A-8EDA-BA545DD3674D
    - SPLUNK_HOST=https://heclb1:8088
    - SPLUNK_INDEX=main
    - SKIP_SSL_VALIDATION_CF=true
    - SKIP_SSL_VALIDATION_SPLUNK=true
  depends_on:
    - trafficcontroller
  restart: always
