trafficcontroller:
  image: zlchen/trafficcontroller:1.1
  hostname: trafficcontroller
  ports:
    - "8081"
    - "9911"
  restart: always

nozzle:
  image: zlchen/nozzle:1.1
  hostname: nozzle
  ports:
    - "9912"
  environment:
    - SPLUNK_TOKEN=00000000-0000-0000-0000-000000000000
    - SPLUNK_HOST=https://so1:8088
    - SKIP_SSL_VALIDATION_CF=true
    - SKIP_SSL_VALIDATION_SPLUNK=true
  depends_on:
    - trafficcontroller
  restart: always
